### ISSUE TITLE
请求数据处理文件

### ISSUE THREAD

**Issue by TangJiakai** [newlei/FairGo#2]
您好！拜读了您的paper和部分code，感受颇深，我想尝试复现效果并在此基础上做一些改进。但是我从您的代码和数据集链接中并未找到完整的数据集处理文件（只看到一小部分处理lastfm的data.py，而且还很不完整，只是提取了user和item的属性部分），希望您可以上传一下处理数据集的py文件，感谢！！！

**Comment by newlei** [comment]
处理好完整的数据集是有的，你可以直接使用。由于处理数据集的步骤繁琐，无法直接提供从原始数据到最终npy的代码。目前的处理lastfm的data.py，只包含了如何处理原始数据，如何得到属性和rating的部分都有，你可以参考。后续还有过滤数据，清洗数据，拆分部分，这部分无法直接提供可处理的代码。

**Comment by TangJiakai** [comment]
感谢您的回答，但还有几个问题：
1. 不知道您对于缺失数据是如何处理的呢？比如age和gender为空的，因为我看您处理前后user 数目都不变，说明您并没有过滤掉user
2. 可否提供如何训练初始的item_emb和user_emb的code呢？因为我看您是直接使用预训练得到的embedding，而非从原始数据端到端训练FairGo的（当然这一点您在paper里面也强调了这是适用于任何模型的，但我想具体了解一下您使用的模型及参数设置等，便于我从头复现）；
3. 在您提供代码里面DisClf**部分的forward，将scores先后经过了log_softmax和CrossEntropyLoss，难道不应该只需要一个CrossEntropyLoss吗？或者说是经过logsoftmax后只需要再使用一个NLLLoss吗？
https://github.com/newlei/FairGo/blob/a0953726eb4997fc87a7c756e6a559e19c343561/code/code_lastfm/filter_layer.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L49-L62
4. paper里面说的VR和VG的比重，也就是说λ设为0.1或者0.2，但我看您代码里实际上VR和VG的比值却为1：1000？具体代码提现到这个地方https://github.com/newlei/FairGo/blob/a0953726eb4997fc87a7c756e6a559e19c343561/code/code_lastfm/FairGo_gcn_remove_age.py#L179-L182
5. 为什么要对rating除一个len_set呢？这个我没有想明白，您可以解释一下吗？
https://github.com/newlei/FairGo/blob/a0953726eb4997fc87a7c756e6a559e19c343561/code/code_lastfm/data_utils.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L64.
6. 看到您训练部分的代码，发现您在每一个epoch过程中都会使用一遍train_set、val_set和test_set，这好像不太妥吧。。。
期待您的回答！

**Comment by newlei** [comment]
1，离处理数据太久，不记得原始是否有缺失属性，你可以确定一下。如果确实按你说的，原始数据有缺失属性，而user数量不变，那么我是采用了填充方式来做的。
2，如你所说CrossEntropyLoss可以不需要log_softmax，感谢你指出来，你也可以看到部分代码是没有log_softmax，部分代码有log_softmax，由于上传时版本错误导致的，后续会更正。
3，剩余问题是基础性问题故不加以说明。如问题2，提取的emb模型就是普通基础模型BPR，GCN，可自行实现，论文中也有交代。
