### ISSUE TITLE
关于数据中的缺失值

### ISSUE THREAD

**Issue by chenfangyi1988** [newlei/FairGo#4]
您好，我注意到原始数据中存在某些缺失值，请问您是使用什么方法填充的呢？非常期待您的回复！

**Comment by newlei** [comment]
能否说一下具体事那些缺失值呢？我这里没有缺失值。如果说的是邻接矩阵的话，里面没有相连的节点就是0。

**Comment by chenfangyi1988** [comment]
我下载了原始数据文件，在usersha1-profile.tsv文件中，部分数据缺少性别和年龄属性值，如下图所示
![image](https://user-images.githubusercontent.com/45649138/175806372-36696de1-712c-4f59-aedf-d081f3e90f71.png)
此外，在usersha1-artmbid-artname-plays.tsv文件中，部分数据缺少musicbrainz-artist-id属性值，请问您是是用什么方法填充的呢？

**Comment by newlei** [comment]
> 我下载了原始数据文件，在usersha1-profile.tsv文件中，部分数据缺少性别和年龄属性值，如下图所示 ![image](https://user-images.githubusercontent.com/45649138/175806372-36696de1-712c-4f59-aedf-d081f3e90f71.png) 此外，在usersha1-artmbid-artname-plays.tsv文件中，部分数据缺少musicbrainz-artist-id属性值，请问您是是用什么方法填充的呢？

正如我们论文中描述的，我们是对原始数据进行了处理的。只保留有属性值的数据。这些有属性缺失的值是直接丢弃的，所以没有填充。
